/**
 * Ceylon SL Gems - Core Data Store
 * Authentic Sri Lankan Gemstones, Certificate Registry, Jewelry Settings, and Exchange Rates
 */

const CURRENCIES = {
    USD: { symbol: '$', rate: 1.0, name: 'USD ($)' },
    LKR: { symbol: 'Rs. ', rate: 305.50, name: 'LKR (Rs.)' },
    EUR: { symbol: '€', rate: 0.92, name: 'EUR (€)' },
    GBP: { symbol: '£', rate: 0.79, name: 'GBP (£)' },
    AUD: { symbol: 'A$', rate: 1.52, name: 'AUD (A$)' },
    AED: { symbol: 'AED ', rate: 3.67, name: 'AED' }
};

const GEMSTONES_DATA = [
    {
        id: "CSG-0101",
        name: "Royal Blue Ceylon Sapphire",
        category: "sapphire",
        mineral: "Natural Corundum",
        color: "Vivid Royal Blue",
        colorFamily: "blue",
        carat: 4.85,
        cut: "Cushion Brilliant",
        shape: "cushion",
        dimensions: "10.4 x 8.6 x 6.2 mm",
        clarity: "Eye Clean (VVS1)",
        treatment: "Natural / Unheated",
        origin: "Ratnapura (City of Gems), Sri Lanka",
        priceUsd: 14500,
        featured: true,
        rarity: "Ultra Rare Investment Grade",
        certificateNo: "CSG-7712-BS",
        lab: "NGJA & GRS Certified",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80",
        description: "An extraordinary unheated Royal Blue Sapphire from the legendary gravel pits of Ratnapura. Possesses the mesmerizing velvety saturation and fire that makes Ceylon blue sapphires celebrated by royalty worldwide.",
        inStock: true
    },
    {
        id: "CSG-0102",
        name: "Imperial Padparadscha Sapphire",
        category: "padparadscha",
        mineral: "Natural Corundum",
        color: "Sunset Pinkish-Orange (Lotus Flower)",
        colorFamily: "orange-pink",
        carat: 3.42,
        cut: "Oval Mixed Cut",
        shape: "oval",
        dimensions: "9.2 x 7.4 x 5.8 mm",
        clarity: "Exceptional Transparency (IF)",
        treatment: "Natural / Unheated",
        origin: "Elahera, Sri Lanka",
        priceUsd: 22800,
        featured: true,
        rarity: "Collector's Holy Grail",
        certificateNo: "CSG-8840-PD",
        lab: "GIA & SSEF Certified",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80",
        description: "The rarest of all corundum varieties. Named after the Sinhalese word for 'lotus blossom' (Padma Raga), capturing the precise delicate blend of tropical sunset pink and vibrant dawn orange.",
        inStock: true
    },
    {
        id: "CSG-0103",
        name: "Cornflower Blue Star Sapphire",
        category: "star-sapphire",
        mineral: "Natural Corundum (Asterism)",
        color: "Vibrant Cornflower Blue",
        colorFamily: "blue",
        carat: 8.65,
        cut: "High Dome Cabochon",
        shape: "cabochon",
        dimensions: "12.8 x 11.2 x 7.9 mm",
        clarity: "Translucent with Sharp 6-Ray Star",
        treatment: "Natural / Unheated",
        origin: "Balangoda, Sri Lanka",
        priceUsd: 11200,
        featured: true,
        rarity: "Museum Grade Asterism",
        certificateNo: "CSG-9104-SS",
        lab: "NGJA Certified",
        image: "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?auto=format&fit=crop&w=800&q=80",
        description: "Features a razor-sharp, perfectly centered 6-ray star that glides effortlessly across the silky blue dome under direct sunlight or spot illumination.",
        inStock: true
    },
    {
        id: "CSG-0104",
        name: "Canary Golden Yellow Sapphire",
        category: "sapphire",
        mineral: "Natural Corundum (Pushparaga)",
        color: "Brilliant Canary Gold",
        colorFamily: "yellow",
        carat: 5.18,
        cut: "Emerald Radiant Cut",
        shape: "emerald",
        dimensions: "10.8 x 8.4 x 5.9 mm",
        clarity: "Loupe Clean (VVS)",
        treatment: "Traditional Heated",
        origin: "Nivithigala, Sri Lanka",
        priceUsd: 6800,
        featured: true,
        rarity: "High Demand Vedic Astrological Grade",
        certificateNo: "CSG-6520-YS",
        lab: "GIC (Gemological Institute of Colombo)",
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80",
        description: "Radiant golden brilliance, revered in Vedic gemology as Pushparaga for prosperity and wisdom. Masterfully cut to deliver maximum scintillation.",
        inStock: true
    },
    {
        id: "CSG-0105",
        name: "Chrysoberyl Cat's Eye (Vaidurya)",
        category: "cats-eye",
        mineral: "Natural Chrysoberyl (Cymophane)",
        color: "Honey Brown 'Milk & Honey'",
        colorFamily: "brown-green",
        carat: 6.70,
        cut: "Oval Cabochon",
        shape: "cabochon",
        dimensions: "11.5 x 9.8 x 6.8 mm",
        clarity: "Sharp Chatoyancy Line",
        treatment: "Natural / Unheated",
        origin: "Pelmadulla, Sri Lanka",
        priceUsd: 16400,
        featured: true,
        rarity: "Exceptional Rarity",
        certificateNo: "CSG-5290-CE",
        lab: "GIA & NGJA Certified",
        image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
        description: "Exhibits the world-famous 'Milk and Honey' optical effect with a razor-thin luminous slit of chatoyant light moving across the honey-toned gemstone.",
        inStock: true
    },
    {
        id: "CSG-0106",
        name: "Hot Pink Ceylon Sapphire",
        category: "sapphire",
        mineral: "Natural Corundum",
        color: "Neon Vivid Magenta Pink",
        colorFamily: "pink",
        carat: 2.95,
        cut: "Round Brilliant",
        shape: "round",
        dimensions: "8.4 x 8.4 x 5.3 mm",
        clarity: "Eye Clean (VS1)",
        treatment: "Natural / Unheated",
        origin: "Ratnapura, Sri Lanka",
        priceUsd: 7900,
        featured: false,
        rarity: "Highly Sought After",
        certificateNo: "CSG-4431-PS",
        lab: "NGJA Certified",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80",
        description: "Intense neon pink luster that captures light from all angles. An extraordinary engagement ring centerpiece mined from the ancient alluvial gravels.",
        inStock: true
    },
    {
        id: "CSG-0107",
        name: "Color-Change Ceylon Alexandrite",
        category: "alexandrite",
        mineral: "Natural Chrysoberyl",
        color: "Emerald Green (Day) to Ruby Red (Incandescent)",
        colorFamily: "multi",
        carat: 1.88,
        cut: "Cushion Cut",
        shape: "cushion",
        dimensions: "7.6 x 6.5 x 4.4 mm",
        clarity: "Clean with Remarkable 90% Color Shift",
        treatment: "Natural / Unheated",
        origin: "Balangoda, Sri Lanka",
        priceUsd: 19500,
        featured: true,
        rarity: "Extreme Collector's Rarity",
        certificateNo: "CSG-3310-AX",
        lab: "GRS & GIA Certified",
        image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=80",
        description: "'Emerald by day, Ruby by night'. A phenomenon stone displaying an enchanting 90% color change under different light sources.",
        inStock: true
    },
    {
        id: "CSG-0108",
        name: "Cobalt Vivid Ceylon Spinel",
        category: "spinel",
        mineral: "Natural Spinel",
        color: "Deep Cobalt Violet-Blue",
        colorFamily: "blue",
        carat: 4.12,
        cut: "Pear Brilliant",
        shape: "pear",
        dimensions: "11.1 x 7.8 x 5.6 mm",
        clarity: "Eye Clean (VVS)",
        treatment: "Natural / Unheated",
        origin: "Ratnapura, Sri Lanka",
        priceUsd: 5400,
        featured: false,
        rarity: "Fine Artisan Grade",
        certificateNo: "CSG-2189-SP",
        lab: "NGJA Certified",
        image: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=800&q=80",
        description: "Natural untreated spinel exhibiting rich refractive dispersion and deep cobalt luster without any enhancement.",
        inStock: true
    },
    {
        id: "CSG-0109",
        name: "Pigeon Blood Star Ruby",
        category: "ruby",
        mineral: "Natural Corundum",
        color: "Deep Vivid Red",
        colorFamily: "red",
        carat: 5.40,
        cut: "Oval Cabochon",
        shape: "cabochon",
        dimensions: "10.6 x 9.1 x 6.4 mm",
        clarity: "Sharp 6-Point Star",
        treatment: "Natural / Unheated",
        origin: "Elahera, Sri Lanka",
        priceUsd: 13800,
        featured: true,
        rarity: "Imperial Quality",
        certificateNo: "CSG-1108-RB",
        lab: "SSEF & NGJA Certified",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
        description: "Magnificent natural ruby with deep crimson tones and an illuminated centered asterism star displaying Sri Lanka's finest crystalline matrix.",
        inStock: true
    },
    {
        id: "CSG-0110",
        name: "Ceylon Royal Blue Sheen Moonstone",
        category: "moonstone",
        mineral: "Feldspar (Adularia)",
        color: "Colorless with Neon Blue Adularescence",
        colorFamily: "white-blue",
        carat: 11.20,
        cut: "High Oval Cabochon",
        shape: "cabochon",
        dimensions: "16.4 x 13.1 x 8.5 mm",
        clarity: "Transparent Glassy Crystal",
        treatment: "Natural / Untreated",
        origin: "Meetiyagoda, Sri Lanka",
        priceUsd: 1850,
        featured: false,
        rarity: "World's Best Moonstone Source",
        certificateNo: "CSG-9023-MS",
        lab: "NGJA Certified",
        image: "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=800&q=80",
        description: "Mined exclusively from the legendary Meetiyagoda pegmatite veins in Southern Sri Lanka, exhibiting the hallmark liquid neon-blue floating sheen.",
        inStock: true
    },
    {
        id: "CSG-0111",
        name: "Tsavorite Green Garnet",
        category: "garnet",
        mineral: "Natural Grossular Garnet",
        color: "Intense Forest Emerald Green",
        colorFamily: "green",
        carat: 3.15,
        cut: "Emerald Cut",
        shape: "emerald",
        dimensions: "9.0 x 7.1 x 5.2 mm",
        clarity: "Eye Clean (VS)",
        treatment: "Natural / Untreated",
        origin: "Ratnapura, Sri Lanka",
        priceUsd: 4600,
        featured: false,
        rarity: "High Brilliance",
        certificateNo: "CSG-7741-TG",
        lab: "GIC Certified",
        image: "https://images.unsplash.com/photo-1615655406736-b37c4fabf923?auto=format&fit=crop&w=800&q=80",
        description: "Stunning forest green with higher refractive index and dispersion than emerald, maintaining pristine brilliance without oiling.",
        inStock: true
    },
    {
        id: "CSG-0112",
        name: "Pure White Sapphire (Leuco Sapphire)",
        category: "sapphire",
        mineral: "Natural Corundum",
        color: "Diamond White / Crystal Clear",
        colorFamily: "white",
        carat: 4.60,
        cut: "Heart Brilliant",
        shape: "heart",
        dimensions: "10.1 x 9.8 x 6.0 mm",
        clarity: "Flawless (IF)",
        treatment: "Natural / Unheated",
        origin: "Balangoda, Sri Lanka",
        priceUsd: 3900,
        featured: false,
        rarity: "Natural Diamond Alternative",
        certificateNo: "CSG-6602-WS",
        lab: "NGJA Certified",
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80",
        description: "Completely natural colorless corundum with Mohs hardness of 9. Cut in a romantic heart brilliant, offering eternal sparkle and ethical luxury.",
        inStock: true
    }
];

const CERTIFICATE_REGISTRY = {
    "CSG-7712-BS": {
        id: "CSG-7712-BS",
        gemName: "Royal Blue Ceylon Sapphire",
        species: "Natural Corundum",
        variety: "Natural Blue Sapphire",
        weight: "4.85 Carats",
        shapeCut: "Cushion Brilliant",
        dimensions: "10.4 x 8.6 x 6.2 mm",
        colorGrade: "Royal Blue (GIA Grade)",
        transparency: "Transparent",
        origin: "Sri Lanka (Ceylon)",
        treatment: "No Indications of Heating (Natural Unheated)",
        issuingLab: "National Gem & Jewellery Authority (NGJA) / GRS Switzerland Co-verified",
        dateIssued: "January 14, 2026",
        status: "VERIFIED AUTHENTIC & TAMPER-PROOF",
        qrVerified: true,
        sealNumber: "LK-NGJA-2026-88910"
    },
    "CSG-8840-PD": {
        id: "CSG-8840-PD",
        gemName: "Imperial Padparadscha Sapphire",
        species: "Natural Corundum",
        variety: "Padparadscha Sapphire",
        weight: "3.42 Carats",
        shapeCut: "Oval Mixed Cut",
        dimensions: "9.2 x 7.4 x 5.8 mm",
        colorGrade: "Pastel Pinkish-Orange",
        transparency: "Transparent (IF)",
        origin: "Sri Lanka (Elahera)",
        treatment: "No Heat / Completely Natural",
        issuingLab: "GIA (Gemological Institute of America) & SSEF Basel",
        dateIssued: "February 02, 2026",
        status: "VERIFIED AUTHENTIC & TAMPER-PROOF",
        qrVerified: true,
        sealNumber: "GIA-SSEF-2026-00412"
    },
    "CSG-9104-SS": {
        id: "CSG-9104-SS",
        gemName: "Cornflower Blue Star Sapphire",
        species: "Natural Corundum",
        variety: "Star Sapphire (Asterism)",
        weight: "8.65 Carats",
        shapeCut: "Cabochon Oval",
        dimensions: "12.8 x 11.2 x 7.9 mm",
        colorGrade: "Cornflower Blue",
        transparency: "Semi-Transparent with 6-Ray Asterism",
        origin: "Sri Lanka (Balangoda)",
        treatment: "Natural Untreated",
        issuingLab: "National Gem & Jewellery Authority (NGJA)",
        dateIssued: "December 18, 2025",
        status: "VERIFIED AUTHENTIC & TAMPER-PROOF",
        qrVerified: true,
        sealNumber: "LK-NGJA-2025-99214"
    },
    "CSG-6520-YS": {
        id: "CSG-6520-YS",
        gemName: "Canary Golden Yellow Sapphire",
        species: "Natural Corundum",
        variety: "Yellow Sapphire (Pushparaga)",
        weight: "5.18 Carats",
        shapeCut: "Emerald Radiant Cut",
        dimensions: "10.8 x 8.4 x 5.9 mm",
        colorGrade: "Vivid Golden Yellow",
        transparency: "Transparent (VVS)",
        origin: "Sri Lanka (Nivithigala)",
        treatment: "Traditional Heated",
        issuingLab: "Gemological Institute of Colombo (GIC)",
        dateIssued: "November 05, 2025",
        status: "VERIFIED AUTHENTIC & TAMPER-PROOF",
        qrVerified: true,
        sealNumber: "GIC-LK-2025-7782"
    },
    "CSG-5290-CE": {
        id: "CSG-5290-CE",
        gemName: "Chrysoberyl Cat's Eye (Vaidurya)",
        species: "Natural Chrysoberyl",
        variety: "Cat's Eye (Chatoyancy)",
        weight: "6.70 Carats",
        shapeCut: "Oval Cabochon",
        dimensions: "11.5 x 9.8 x 6.8 mm",
        colorGrade: "Honey Brown 'Milk & Honey'",
        transparency: "Translucent with Crisp Central Line",
        origin: "Sri Lanka (Pelmadulla)",
        treatment: "Unheated & Untreated",
        issuingLab: "GIA & NGJA Co-Certified",
        dateIssued: "January 28, 2026",
        status: "VERIFIED AUTHENTIC & TAMPER-PROOF",
        qrVerified: true,
        sealNumber: "GIA-NGJA-2026-66321"
    }
};

const JEWELRY_SETTINGS = [
    {
        id: "solitaire-ring",
        name: "Royal Solitaire Ring Setting",
        category: "ring",
        basePriceUsd: 850,
        description: "Classic 4-prong elevated crown setting engineered to maximize light refraction through your Ceylon gemstone.",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "halo-ring",
        name: "Diamond Halo Cathedral Ring",
        category: "ring",
        basePriceUsd: 1450,
        description: "Framed by 24 brilliant VS1 pavé diamonds (0.45ct total) with cathedral shoulders for a regal silhouette.",
        image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "vintage-pendant",
        name: "Kandyan Heritage Royal Pendant",
        category: "pendant",
        basePriceUsd: 1150,
        description: "Intricately filigreed Ceylon royal motif bail with halo accents, suspended from an 18-inch matching chain.",
        image: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "three-stone-ring",
        name: "Trilogy Tapered Baguette Ring",
        category: "ring",
        basePriceUsd: 1650,
        description: "Flanked by two precision-cut tapered diamond baguettes (0.50ct total) representing past, present, and future.",
        image: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=600&q=80"
    }
];

const METALS_DATA = [
    { id: "18k-yellow", name: "18K Ceylon Yellow Gold", priceMultiplier: 1.0, hex: "#E5C158", purity: "750 Hallmark" },
    { id: "18k-white", name: "18K Radiant White Gold (Rhodium Plated)", priceMultiplier: 1.05, hex: "#EAEAEA", purity: "750 Hallmark" },
    { id: "18k-rose", name: "18K Romantic Rose Gold", priceMultiplier: 1.02, hex: "#ECC5B8", purity: "750 Hallmark" },
    { id: "950-platinum", name: "Platinum 950 Pure Luxury", priceMultiplier: 1.35, hex: "#D3D7DC", purity: "950 Pure" }
];
